/**
 * Custom Template Plugin
 * Adds custom project templates to TryForge
 */

const path = require('path');

module.exports = {
  name: 'custom-template',
  version: '1.0.0',
  description: 'Custom template plugin',

  /**
   * Get available templates
   */
  templates: {
    'minimal-api': {
      name: 'Minimal API',
      description: 'Lightweight REST API template',
      framework: 'express',
      features: ['api', 'minimal'],
      files: [
        'server.js',
        'routes/index.js',
        'middleware/error.js',
        'config/index.js'
      ]
    },
    'fullstack-app': {
      name: 'Full Stack Application',
      description: 'Complete full-stack template with React frontend and Express backend',
      framework: 'react-express',
      features: ['frontend', 'backend', 'database', 'auth'],
      files: [
        'client/',
        'server/',
        'shared/',
        'docker-compose.yml'
      ]
    }
  },

  /**
   * Initialize plugin
   */
  async init(api) {
    api.logger.info('Custom Template plugin initialized');

    // Register template loading hook
    api.hooks.addFilter('template:load', async (templates, context) => {
      api.logger.debug('Adding custom templates...');

      // Add our custom templates
      return {
        ...templates,
        ...this.templates
      };
    });

    // Register template rendering hook
    api.hooks.before('template:render', async (context) => {
      const templateName = context.template;

      if (this.templates[templateName]) {
        api.logger.info(`Using custom template: ${templateName}`);

        // Add custom template data
        context.customTemplate = true;
        context.templateSource = 'custom-template-plugin';
      }

      return context;
    });

    // Add CLI command for listing custom templates
    api.cli.addCommand('templates:custom', {
      description: 'List available custom templates',
      action: async () => {
        console.log('\n📋 Custom Templates:\n');

        for (const [key, template] of Object.entries(this.templates)) {
          console.log(`  ${key}`);
          console.log(`    Name: ${template.name}`);
          console.log(`    Description: ${template.description}`);
          console.log(`    Framework: ${template.framework}`);
          console.log(`    Features: ${template.features.join(', ')}`);
          console.log('');
        }
      }
    });

    // Add template generation command
    api.cli.addCommand('generate:custom', {
      description: 'Generate project from custom template',
      action: async (options) => {
        const templateName = options.template;

        if (!templateName) {
          api.logger.error('Please specify a template with --template');
          return;
        }

        if (!this.templates[templateName]) {
          api.logger.error(`Template not found: ${templateName}`);
          api.logger.info(`Available templates: ${Object.keys(this.templates).join(', ')}`);
          return;
        }

        api.logger.info(`Generating from template: ${templateName}`);
        await this.generateFromTemplate(templateName, options, api);
      }
    });
  },

  /**
   * Generate project from custom template
   */
  async generateFromTemplate(templateName, options, api) {
    const template = this.templates[templateName];
    const projectPath = options.path || process.cwd();

    api.logger.info('Creating project structure...');

    // Create template files
    for (const file of template.files) {
      const filePath = path.join(projectPath, file);

      if (file.endsWith('/')) {
        // Directory
        await api.fs.ensureDir(filePath);
        api.logger.debug(`Created directory: ${file}`);
      } else {
        // File
        const content = await this.getTemplateContent(templateName, file, options);
        await api.fs.writeFile(filePath, content);
        api.logger.debug(`Created file: ${file}`);
      }
    }

    api.logger.success(`Project generated from ${template.name} template!`);
  },

  /**
   * Get template file content
   */
  async getTemplateContent(templateName, fileName, options) {
    // In a real plugin, this would load actual template files
    // For this example, we'll generate simple content

    const template = this.templates[templateName];

    if (fileName === 'server.js') {
      return `// ${template.name}
// Generated by custom-template-plugin

const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Hello from ${template.name}!' });
});

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});
`;
    }

    if (fileName === 'routes/index.js') {
      return `// Routes
const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ message: 'API Routes' });
});

module.exports = router;
`;
    }

    if (fileName === 'package.json') {
      return JSON.stringify({
        name: options.name || 'custom-project',
        version: '1.0.0',
        description: template.description,
        main: 'server.js',
        scripts: {
          start: 'node server.js',
          dev: 'nodemon server.js'
        },
        dependencies: {
          express: '^4.18.2'
        }
      }, null, 2);
    }

    return `// ${fileName}\n// Generated by ${template.name}\n`;
  },

  /**
   * Cleanup
   */
  async destroy() {
    console.log('Custom Template plugin unloaded');
  }
};
