/**
 * Claude Backend Generator
 * Claude generates backend code directly (no external AI service needed)
 */

const fs = require('fs-extra');
const path = require('path');

class ClaudeBackend {
  async generateBackend(architecture, projectName) {
    const backendDir = path.join(projectName, 'backend');

    // Create backend structure
    await this.createStructure(backendDir);

    // Generate database schema
    const schema = await this.generateDatabaseSchema(architecture.database);

    // Generate API routes
    const routes = await this.generateAPIRoutes(architecture.api);

    // Generate models
    const models = await this.generateModels(architecture.database);

    // Generate tests
    const tests = await this.generateTests(architecture);

    return {
      files: [...schema.files, ...routes.files, ...models.files, ...tests.files],
      endpoints: architecture.api.endpoints,
      tables: architecture.database.tables,
    };
  }

  async createStructure(backendDir) {
    const dirs = [
      'src/routes',
      'src/models',
      'src/middleware',
      'src/services',
      'src/utils',
      'sql',
      'tests',
    ];

    for (const dir of dirs) {
      await fs.ensureDir(path.join(backendDir, dir));
    }
  }

  async generateDatabaseSchema(databasePlan) {
    // Generate SQL schema
    const schema = `-- Database Schema
-- Auto-generated by TryForge

${databasePlan.tables.map(table => `
CREATE TABLE ${table} (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`).join('\n')}
`;

    return {
      files: [{ name: 'schema.sql', content: schema }],
    };
  }

  async generateAPIRoutes(apiPlan) {
    // Generate Express routes
    return {
      files: apiPlan.endpoints.map(endpoint => ({
        name: `${endpoint.path.split('/')[2]}.js`,
        content: `// ${endpoint.method} ${endpoint.path}\n// Auto-generated by TryForge\n`,
      })),
    };
  }

  async generateModels(databasePlan) {
    return {
      files: databasePlan.tables.map(table => ({
        name: `${table}.js`,
        content: `// Model: ${table}\n// Auto-generated by TryForge\n`,
      })),
    };
  }

  async generateTests(architecture) {
    return {
      files: [{ name: 'api.test.js', content: '// Tests\n' }],
    };
  }
}

module.exports = ClaudeBackend;
