/**
 * Memory System
 * Saves all operations in markdown files for unlimited context
 */

const fs = require('fs-extra');
const path = require('path');
const markdown = require('markdown-it')();

class MemorySystem {
  constructor(projectPath = process.cwd()) {
    this.projectPath = projectPath;
    this.memoryDir = path.join(projectPath, '.bolt-memory');
    this.ensure Directories();
  }

  /**
   * Ensure memory directories exist
   */
  ensureDirectories() {
    const dirs = [
      this.memoryDir,
      path.join(this.memoryDir, 'backups'),
      path.join(this.memoryDir, 'changes'),
      path.join(this.memoryDir, 'decisions'),
      path.join(this.memoryDir, 'sessions'),
    ];

    dirs.forEach(dir => fs.ensureDirSync(dir));
  }

  /**
   * Record application creation
   */
  static async recordCreation(data) {
    const memory = new MemorySystem();
    const timestamp = new Date().toISOString();
    const filename = `${timestamp.split('T')[0]}_creation.md`;
    const filepath = path.join(memory.memoryDir, 'changes', filename);

    const content = `# Application Creation

## Session Info
- **Date:** ${timestamp}
- **Description:** ${data.description}
- **Project:** ${data.projectName}

## Analysis
- **Type:** ${data.analysis.type}
- **Features:** ${data.analysis.features.join(', ')}
- **Tech Stack:** ${data.analysis.techStack.join(', ')}

## Architecture
- **Database Tables:** ${data.architecture.database.tables.length}
- **API Endpoints:** ${data.architecture.api.endpoints.length}
- **Frontend Components:** ${data.architecture.frontend.components.length}
- **Graphics Generated:** ${data.results.graphics.length}

## Results
- **Total Files:** ${data.results.stats.totalFiles}
- **Duration:** ${data.results.stats.duration}
- **Status:** ✅ Success

## Components Generated
${data.results.frontend.map(c => `- ${c.name}`).join('\n')}

## Graphics Generated
${data.results.graphics.map(g => `- ${g.name}: ${g.path}`).join('\n')}

---
*Generated by TryForge Triple AI Framework*
`;

    await fs.writeFile(filepath, content);
    await memory.updateIndex();
  }

  /**
   * Record refactoring session
   */
  static async recordRefactoring(data) {
    const memory = new MemorySystem();
    const timestamp = new Date().toISOString();
    const filename = `${timestamp.split('T')[0]}_refactoring.md`;
    const filepath = path.join(memory.memoryDir, 'changes', filename);

    const content = `# Refactoring Session

## Session Info
- **Date:** ${timestamp}
- **Description:** ${data.description}

## Improvements Selected
${data.selectedImprovements.map(i => `- ${i.category}: ${i.title}`).join('\n')}

## Results
- **Files Modified:** ${data.results.stats.modified}
- **Files Added:** ${data.results.stats.added}
- **Status:** ✅ Complete

---
*Generated by TryForge Triple AI Framework*
`;

    await fs.writeFile(filepath, content);
    await memory.updateIndex();
  }

  /**
   * Update main memory index
   */
  async updateIndex() {
    const indexPath = path.join(this.memoryDir, 'index.md');

    const recentChanges = await this.getRecentChanges(7);

    const content = `# Project Memory Index

**Last Updated:** ${new Date().toISOString()}
**Project:** ${path.basename(this.projectPath)}

## Recent Activity (Last 7 Days)

${recentChanges.map(c => `- ${c.date}: ${c.title}`).join('\n')}

## Quick Stats
- Total Sessions: ${await this.countSessions()}
- Total Changes: ${await this.countChanges()}

---
*Auto-generated by TryForge Memory System*
`;

    await fs.writeFile(indexPath, content);
  }

  /**
   * Get recent changes
   */
  async getRecentChanges(days) {
    const changesDir = path.join(this.memoryDir, 'changes');
    const files = await fs.readdir(changesDir);

    return files
      .filter(f => f.endsWith('.md'))
      .slice(0, days)
      .map(f => ({
        date: f.split('_')[0],
        title: f.split('_')[1]?.replace('.md', ''),
      }));
  }

  /**
   * Count total sessions
   */
  async countSessions() {
    const sessionsDir = path.join(this.memoryDir, 'sessions');
    const files = await fs.readdir(sessionsDir).catch(() => []);
    return files.length;
  }

  /**
   * Count total changes
   */
  async countChanges() {
    const changesDir = path.join(this.memoryDir, 'changes');
    const files = await fs.readdir(changesDir).catch(() => []);
    return files.length;
  }
}

module.exports = MemorySystem;
